// Mock data for development
import { App } from './types';

export const mockApps: App[] = [
  {
    id: '1',
    name: 'Centrepoint',
    os: 'ios',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-26T14:30:00Z',
    deployments: [
      {
        id: 'd1',
        name: 'Production',
        key: 'prod-key-abc123',
        releases: [
          {
            id: 'r1',
            label: 'v42',
            appVersion: '2.1.0',
            description: 'Fixed critical bug in payment flow',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 2457600,
            uploadTime: '2024-01-26T10:30:00Z',
            isMandatory: true,
            isDisabled: false,
            metrics: {
              active: 8234,
              downloaded: 9876,
              failed: 45,
              installed: 9521,
              totalDevices: 10000,
            },
          },
          {
            id: 'r2',
            label: 'v41',
            appVersion: '2.0.9',
            description: 'Performance improvements and UI polish',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 2398720,
            uploadTime: '2024-01-24T15:20:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 1234,
              downloaded: 2345,
              failed: 12,
              installed: 2298,
              totalDevices: 2500,
            },
          },
          {
            id: 'r3',
            label: 'v40',
            appVersion: '2.0.8',
            description: 'Added new dashboard features',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 2301440,
            uploadTime: '2024-01-20T09:15:00Z',
            isMandatory: false,
            isDisabled: true,
            metrics: {
              active: 0,
              downloaded: 567,
              failed: 8,
              installed: 534,
              totalDevices: 600,
            },
          },
        ],
      },
      {
        id: 'd2',
        name: 'Staging',
        key: 'staging-key-def456',
        releases: [
          {
            id: 'r4',
            label: 'v12',
            appVersion: '2.2.0-beta',
            description: 'Testing new analytics integration',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 2587648,
            uploadTime: '2024-01-26T08:00:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 45,
              downloaded: 52,
              failed: 2,
              installed: 48,
              totalDevices: 50,
            },
          },
        ],
      },
    ],
  },
  {
    id: '2',
    name: 'Homecentre',
    os: 'android',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-25T16:45:00Z',
    deployments: [
      {
        id: 'd3',
        name: 'Production',
        key: 'prod-key-ghi789',
        releases: [
          {
            id: 'r5',
            label: 'v38',
            appVersion: '2.1.0',
            description: 'Material Design 3 update',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 3145728,
            uploadTime: '2024-01-25T11:00:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 15234,
              downloaded: 18765,
              failed: 89,
              installed: 17234,
              totalDevices: 20000,
            },
          },
          {
            id: 'r6',
            label: 'v37',
            appVersion: '2.0.9',
            description: 'Bug fixes for Android 14',
            releaseMethod: 'Upload',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 3098624,
            uploadTime: '2024-01-22T14:30:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 3456,
              downloaded: 4567,
              failed: 23,
              installed: 4321,
              totalDevices: 5000,
            },
          },
        ],
      },
      {
        id: 'd4',
        name: 'Staging',
        key: 'staging-key-jkl012',
        releases: [
          {
            id: 'r7',
            label: 'v15',
            appVersion: '2.2.0-beta',
            description: 'Testing new push notification system',
            releaseMethod: 'Promote',
            releasedBy: 'sushil.sharma@gmail.com',
            size: 3201024,
            uploadTime: '2024-01-26T09:30:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 78,
              downloaded: 85,
              failed: 3,
              installed: 80,
              totalDevices: 100,
            },
          },
        ],
      },
    ],
  },
  {
    id: '3',
    name: 'Centrepoint',
    os: 'android',
    createdAt: '2023-11-20T08:00:00Z',
    updatedAt: '2024-01-24T12:00:00Z',
    deployments: [
      {
        id: 'd5',
        name: 'Production',
        key: 'prod-key-mno345',
        releases: [
          {
            id: 'r8',
            label: 'v23',
            appVersion: '1.5.2',
            description: 'Inventory management improvements',
            releaseMethod: 'Upload',
            releasedBy: 'david@retail.com',
            size: 4194304,
            uploadTime: '2024-01-24T10:00:00Z',
            isMandatory: true,
            isDisabled: false,
            metrics: {
              active: 456,
              downloaded: 502,
              failed: 5,
              installed: 487,
              totalDevices: 500,
            },
          },
        ],
      },
    ],
  },
  {
    id: '4',
    name: 'Homecentre',
    os: 'ios',
    createdAt: '2023-10-10T12:00:00Z',
    updatedAt: '2024-01-23T09:20:00Z',
    deployments: [
      {
        id: 'd6',
        name: 'Production',
        key: 'prod-key-pqr678',
        releases: [
          {
            id: 'r9',
            label: 'v67',
            appVersion: '3.2.1',
            description: 'Added heart rate monitoring',
            releaseMethod: 'Upload',
            releasedBy: 'jane@health.com',
            size: 5242880,
            uploadTime: '2024-01-23T08:00:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 2345,
              downloaded: 2678,
              failed: 18,
              installed: 2567,
              totalDevices: 3000,
            },
          },
          {
            id: 'r10',
            label: 'v66',
            appVersion: '3.2.0',
            description: 'UI refresh for health dashboard',
            releaseMethod: 'Upload',
            releasedBy: 'tom@health.com',
            size: 5111808,
            uploadTime: '2024-01-18T13:45:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 234,
              downloaded: 345,
              failed: 6,
              installed: 312,
              totalDevices: 400,
            },
          },
        ],
      },
      {
        id: 'd7',
        name: 'Beta',
        key: 'beta-key-stu901',
        releases: [
          {
            id: 'r11',
            label: 'v5',
            appVersion: '3.3.0-beta',
            description: 'Testing sleep tracking feature',
            releaseMethod: 'Upload',
            releasedBy: 'susan@health.com',
            size: 5376000,
            uploadTime: '2024-01-25T16:00:00Z',
            isMandatory: false,
            isDisabled: false,
            metrics: {
              active: 89,
              downloaded: 95,
              failed: 1,
              installed: 92,
              totalDevices: 100,
            },
          },
        ],
      },
    ],
  },
];

