import { ReleaseNoteConfig } from '../types/releaseNote';

export const releaseNoteConfigs: ReleaseNoteConfig[] = [
  {
    type: 'Hybris Hotfix',
    columns: [
      { id: 'hotfixDate', label: 'Hotfix date', type: 'date', required: true, width: '120px' },
      { id: 'hotfixBranch', label: 'Hotfix branch', type: 'text', required: true, width: '200px' },
      { id: 'crNumber', label: 'CR', type: 'text', width: '100px' },
      { id: 'description', label: 'Description', type: 'textarea', width: '300px' },
      { id: 'hot', label: 'HoT', type: 'text', width: '100px' },
      { id: 'em', label: 'EM', type: 'text', width: '100px' },
      { id: 'systemUpdate', label: 'System Update', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'codePush', label: 'Code Push', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'impex', label: 'Impex', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'appSubmission', label: 'App Submission', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'enableMode', label: 'Enable mode', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'reactNative', label: 'React Native', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'microservice', label: 'Microservice', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'db', label: 'DB', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'comment', label: 'Comm', type: 'textarea', width: '200px' },
    ]
  },
  {
    type: 'BLC Hotfix',
    columns: [
      { id: 'hotfixDate', label: 'Hotfix Date', type: 'date', required: true, width: '120px' },
      { id: 'hotfixBranch', label: 'Branch Name', type: 'text', required: true, width: '200px' },
      { id: 'crNumber', label: 'CR Number (Change Request)', type: 'text', width: '150px' },
      { id: 'featureList', label: 'Feature List', type: 'textarea', width: '300px' },
      { id: 'productionBugList', label: 'Production Bug List', type: 'textarea', width: '300px' },
      { id: 'description', label: 'Description', type: 'textarea', width: '300px' },
      { id: 'state', label: 'Current State', type: 'select', options: ['Draft', 'In Review', 'Approved', 'Released', 'Rolled Back'], width: '120px' },
      { id: 'theme', label: 'Theme', type: 'text', width: '150px' },
      { id: 'scrumMaster', label: 'Scrum Master', type: 'text', width: '150px' },
      { id: 'po', label: 'PO', type: 'text', width: '100px' },
      { id: 'hot', label: 'HoT', type: 'text', width: '100px' },
      { id: 'em', label: 'EM', type: 'text', width: '100px' },
      { id: 'apiChanges', label: 'New/Existing API Changes', type: 'textarea', width: '200px' },
      { id: 'systemUpdate', label: 'System Update', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'codePush', label: 'Code Push', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'impex', label: 'Impex', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'appSubmission', label: 'App Submission', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'enableMode', label: 'Enable Mode ?', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'reactNative', label: 'React Native', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'microservice', label: 'Microservice', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'db', label: 'DB', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'comment', label: 'Comment', type: 'textarea', width: '200px' },
    ]
  },
  {
    type: 'LMD Theme Release',
    columns: [
      { id: 'releaseDate', label: 'Release Date', type: 'date', required: true, width: '120px' },
      { id: 'artComponents', label: 'ART Components', type: 'text', width: '150px' },
      { id: 'featureList', label: 'Feature List', type: 'textarea', width: '300px' },
      { id: 'ptRequired', label: 'PT Required?', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'walkthrough', label: 'Walkthrough w/ Regression & Support', type: 'select', options: ['Yes', 'No'], width: '200px' },
      { id: 'apiChanges', label: 'New/Existing API Changes', type: 'textarea', width: '200px' },
      { id: 'theme', label: 'Theme', type: 'text', width: '150px' },
      { id: 'scrumMaster', label: 'Scrum Master', type: 'text', width: '150px' },
      { id: 'po', label: 'PO', type: 'text', width: '100px' },
      { id: 'hot', label: 'HoT', type: 'text', width: '100px' },
      { id: 'em', label: 'EM', type: 'text', width: '100px' },
      { id: 'lpo', label: 'LPO', type: 'text', width: '100px' },
      { id: 'stageHybris', label: 'Stage Hybris', type: 'text', width: '150px' },
      { id: 'systemUpdate', label: 'System Update', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'codePush', label: 'Code Push', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'impex', label: 'Impex', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'appSubmission', label: 'App Submission', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'enableMode', label: 'Enable Mode ?', type: 'select', options: ['Yes', 'No'], width: '120px' },
      { id: 'reactNative', label: 'React Native', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'react', label: 'React', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'microservice', label: 'Microservice', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'oms', label: 'OMS', type: 'text', width: '100px' },
      { id: 'rms', label: 'RMS', type: 'text', width: '100px' },
      { id: 'orpos', label: 'ORPOS', type: 'text', width: '100px' },
      { id: 'ofin', label: 'OFIN', type: 'text', width: '100px' },
      { id: 'rpas', label: 'RPAS', type: 'text', width: '100px' },
      { id: 'hcm', label: 'HCM', type: 'text', width: '100px' },
      { id: 'plm', label: 'PLM', type: 'text', width: '100px' },
      { id: 'spaceManagement', label: 'Space Management', type: 'text', width: '150px' },
      { id: 'wms', label: 'WMS', type: 'text', width: '100px' },
      { id: 'contentCentral', label: 'Content Central', type: 'text', width: '150px' },
      { id: 'oracleFinancials', label: 'Oracle Financials', type: 'text', width: '150px' },
      { id: 'treasuryManagement', label: 'Treasury Management', type: 'text', width: '150px' },
      { id: 'rib', label: 'RIB', type: 'text', width: '100px' },
      { id: 'moengage', label: 'Moengage', type: 'text', width: '100px' },
      { id: 'shukranDigital', label: 'Shukran Digital', type: 'text', width: '150px' },
      { id: 'shukranPay', label: 'Shukran Pay', type: 'text', width: '150px' },
      { id: 'dynamicAction', label: 'Dynamic Action', type: 'text', width: '150px' },
      { id: 'epsilon', label: 'Epsilon', type: 'text', width: '100px' },
      { id: 'whatsapp', label: 'Whatsapp', type: 'text', width: '100px' },
      { id: 'nginxGateway', label: 'NGINX Gateway', type: 'text', width: '150px' },
      { id: 'blc', label: 'BLC', type: 'text', width: '100px' },
      { id: 'algolia', label: 'Algolia', type: 'text', width: '100px' },
      { id: 'dataManager', label: 'Data Manager', type: 'text', width: '150px' },
      { id: 'plReport', label: 'PL Report', type: 'text', width: '100px' },
      { id: 'cowrite', label: 'Cowrite', type: 'text', width: '100px' },
      { id: 'ogloba', label: 'Ogloba', type: 'text', width: '100px' },
      { id: 'sim', label: 'SIM', type: 'text', width: '100px' },
      { id: 'ssm', label: 'SSM', type: 'text', width: '100px' },
      { id: 'sahlaStore', label: 'Sahla Store', type: 'text', width: '150px' },
      { id: 'dematic', label: 'Dematic', type: 'text', width: '100px' },
      { id: 'sahlaWh', label: 'Sahla WH', type: 'text', width: '150px' },
      { id: 'rfidSml', label: 'RFID/SML', type: 'text', width: '100px' },
      { id: 'sahlaPortal', label: 'Sahla Portal', type: 'text', width: '150px' },
      { id: 'locus', label: 'LOCUS', type: 'text', width: '100px' },
      { id: 'gdms', label: 'GDMS', type: 'text', width: '100px' },
      { id: 'netezza', label: 'Netezza + Qlik/Power BI', type: 'text', width: '200px' },
      { id: 'tams', label: 'TAMS', type: 'text', width: '100px' },
      { id: 'e2open', label: 'E2Open', type: 'text', width: '100px' },
      { id: 'wooqer', label: 'Wooqer/Sahlati', type: 'text', width: '150px' },
      { id: 's2p2p', label: 'S2P2P', type: 'text', width: '100px' },
      { id: 'apiGateway', label: 'API Gateway', type: 'text', width: '150px' },
      { id: 'ace', label: 'ACE', type: 'text', width: '100px' },
      { id: 'db', label: 'DB', type: 'select', options: ['Yes', 'No'], width: '80px' },
      { id: 'cab', label: 'CAB (Y/N) If yes, #CR', type: 'text', width: '200px' },
      { id: 'reactWeb', label: 'React WEB', type: 'select', options: ['Yes', 'No'], width: '100px' },
      { id: 'comment', label: 'Comment', type: 'textarea', width: '200px' },
    ]
  }
];
